# File Variables
@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Auth endpoint
# @prompt username
# @prompt password
# @name login
POST http://{{host}}/api/auth/ HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### API Home
POST http://{{host}}/api/ HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "My Product",
    "content": "Hello world"
}

### Get list of products
GET http://{{host}}/api/products/ HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

### Get a product
# @prompt productId
GET http://{{host}}/api/products/{{productId}}/ HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}

### Create a product
POST http://{{host}}/api/products/ HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}

{
    "title": "New Product",
    "price": 25.00
}

### Update a product
# @prompt productId
PUT http://{{host}}/api/products/{{productId}}/update HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}

{
    "title": "Hello world my old friend",
    "price": 99.99
}

### Delete a product
# @prompt productId
DELETE http://{{host}}/api/products/{{productId}}/delete HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
